### ISSUE TITLE
windows系统下疑似webpack 解析svg插件失败

### ISSUE THREAD

**Issue by swqddx** [ecomfe/reskript#114]
PS D:\baidu\workflow\developer-fe> npm start

> res-demo@1.0.0 start D:\baidu\workflow\developer-fe
> skr dev

× @reskript/dev
  Compiled with some errors in 10.49s

i ｢wds｣: Project is running at http://0.0.0.0:2021/
i ｢wds｣: webpack output is served from /assets/
i ｢wds｣: Content not from webpack is served from D:\baidu\workflow\developer-fe
i ｢wds｣: 404s will fallback to /assets/index.html

 ERROR  Failed to compile with 3 errors                                                                                        下午4:23:09
 error  in Daiduworkflowdeveloper-fesrccomponentsAppassets      ab_erweima.svg?asset

Module build failed: UnhandledSchemeError: Reading from "Daiduworkflowdeveloper-fesrccomponentsAppassets        ab_erweima.svg?asset" is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "d:" URIs.
    at D:\baidu\workflow\developer-fe\node_modules\webpack\lib\NormalModule.js:787:26
    at Hook.eval [as callAsync] (eval at create (D:\baidu\workflow\developer-fe\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (D:\baidu\workflow\developer-fe\node_modules\tapable\lib\Hook.js:18:14)
    at Object.processResource (D:\baidu\workflow\developer-fe\node_modules\webpack\lib\NormalModule.js:784:9)
    at processResource (D:\baidu\workflow\developer-fe\node_modules\loader-runner\lib\LoaderRunner.js:220:11)
    at iteratePitchingLoaders (D:\baidu\workflow\developer-fe\node_modules\loader-runner\lib\LoaderRunner.js:171:10)
    at runLoaders (D:\baidu\workflow\developer-fe\node_modules\loader-runner\lib\LoaderRunner.js:397:2)
    at NormalModule.doBuild (D:\baidu\workflow\developer-fe\node_modules\webpack\lib\NormalModule.js:773:3)
    at NormalModule.build (D:\baidu\workflow\developer-fe\node_modules\webpack\lib\NormalModule.js:920:15)
    at D:\baidu\workflow\developer-fe\node_modules\webpack\lib\Compilation.js:1322:12

 error  in Daiduworkflowdeveloper-fesrccomponentsAppassets      ab_web.svg?asset

Module build failed: UnhandledSchemeError: Reading from "Daiduworkflowdeveloper-fesrccomponentsAppassets        ab_web.svg?asset" is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "d:" URIs.
    at D:\baidu\workflow\developer-fe\node_modules\webpack\lib\NormalModule.js:787:26
    at Hook.eval [as callAsync] (eval at create (D:\baidu\workflow\developer-fe\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Object.processResource (D:\baidu\workflow\developer-fe\node_modules\webpack\lib\NormalModule.js:784:9)
    at processResource (D:\baidu\workflow\developer-fe\node_modules\loader-runner\lib\LoaderRunner.js:220:11)
    at iteratePitchingLoaders (D:\baidu\workflow\developer-fe\node_modules\loader-runner\lib\LoaderRunner.js:171:10)
    at runLoaders (D:\baidu\workflow\developer-fe\node_modules\loader-runner\lib\LoaderRunner.js:397:2)
    at NormalModule.doBuild (D:\baidu\workflow\developer-fe\node_modules\webpack\lib\NormalModule.js:773:3)
    at NormalModule.build (D:\baidu\workflow\developer-fe\node_modules\webpack\lib\NormalModule.js:920:15)
    at D:\baidu\workflow\developer-fe\node_modules\webpack\lib\Compilation.js:1322:12
    at NormalModule.needBuild (D:\baidu\workflow\developer-fe\node_modules\webpack\lib\NormalModule.js:1195:26)

 error  

Cannot read property 'get' of undefined
during rendering of asset asset/resource|Daiduworkflowdeveloper-fesrccomponentsAppassets        ab_erweima.svg?asset

**Comment by otakustay** [comment]
能否提供一下你引用`ab_erweima.svg`这个文件的代码？即那个`import`说一句

**Comment by swqddx** [comment]
> 能否提供一下你引用`ab_erweima.svg`这个文件的代码？即那个`import`语句

`import tab_erweima from '@/components/App/assets/tab_erweima.svg';`

**Comment by otakustay** [comment]
我在Windows下出现的问题还不太一样，不过尝试修复了一下，在Windows 11 ARM64上倒是能用

<img width="1011" alt="CleanShot 2021-08-17 at 19 05 50@2x" src="https://user-images.githubusercontent.com/639549/129715626-960cc749-e175-428e-a4d7-e12fa92a7293.png">

回头先发个版本试试吧

**Comment by otakustay** [comment]
@swqddx 这个Windows环境是否有其它的软件？比如命令行用的是啥，是原生的cmd吗？
