### ISSUE TITLE
jest无法处理babel生成的ESM代码

### ISSUE THREAD

**Issue by otakustay** [ecomfe/reskript#115]
```
node_modules/@babel/runtime/helpers/esm/extends.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){export default function _extends() {
                                                                                      ^^^^^^

    SyntaxError: Unexpected token 'export'

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1479:14)
      at Object.<anonymous> (node_modules/antd/es/input/Input.js:1:1)
```

下面这个正则是不够健壮的，但也不知道怎么办了：

```
transformIgnorePatterns: [
    // `node_modules`下所有有`es`目录的包，认为发布的是ES代码，要过babel，下面的正则再看一下怎么优化
    'node_modules/[^/]+?/(?!(es|esm|node_modules)/)',
],
```

**Comment by xiayanxiang** [comment]
请问你解决了嘛，我也遇到了这个问题
