### ISSUE TITLE
transformer.getCacheKey 的参数和jest的对不上

### ISSUE THREAD

**Issue by nick-ChenZe** [ecomfe/reskript#68]
执行 skr run test ./someDir

```
 FAIL  src/@standard/components/Popover/__tests__/useEstimatedCostHistory.test.ts
  ● Test suite failed to run

    TypeError: Cannot destructure property 'config' of 'cacheKeyOptions' as it is undefined.

      at Object.getCacheKey (node_modules/@reskript/config-jest/node_modules/babel-jest/build/index.js:217:14)
      at ScriptTransformer._getCacheKey (node_modules/@jest/transform/build/ScriptTransformer.js:281:41)
      at ScriptTransformer._getFileCachePath (node_modules/@jest/transform/build/ScriptTransformer.js:352:27)
      at ScriptTransformer.transformSource (node_modules/@jest/transform/build/ScriptTransformer.js:589:32)
      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:759:40)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:816:19)
```

(node_modules/@jest/transform/build/ScriptTransformer.js:281:41)
```
      transformerCacheKey = transformer.getCacheKey(
        fileData,
        filename,
        transformOptions
      );
    }
```

node_modules/@reskript/config-jest/node_modules/babel-jest/build/index.js:217:14)
```
    getCacheKey(fileData, filename, configString, cacheKeyOptions) {
      const {config, instrument, rootDir} = cacheKeyOptions;
      const babelOptions = loadBabelConfig(
        config.cwd,
        filename,
        cacheKeyOptions
      );
```

看上去个 getCacheKey 两个函数的参数没对上，需要我对齐版本吗, cli 和 test 都是1.6.0

**Comment by nick-ChenZe** [comment]
@reskript/jest-config 之前是1.4.0 升级到1.6.0后解决了
